language: node_js
node_js:
  - "9.9.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
install:
  - yarn install --frozen-lockfile
script:
  - yarn test
