export const langToContent = {
    de: {
        headline: 'Diese Website verwendet Cookies',
        bodyParagraphScreenOne: 'Fandom und unsere Partner verwenden auf unserer Website Technologien wie z. B. Cookies. Um dem zuzustimmen, klicke bitte auf „AKZEPTIEREN“. Ansonsten wähle bitte „MEHR ERFAHREN“ aus.',
        bodyPargraphScreenTwo: 'Fandom und unsere Partner verwenden auf unserer Website Technologien wie z. B. Cookies, um Inhalte und Werbung zu personalisieren, Social-Media-Funktionen bereitzustellen und unseren Website-Verkehr zu analysieren. Wir möchten dich besonders auf Cookies aufmerksam machen, die zu Marketingzwecken verwendet werden oder um dir personalisierte Werbung anzuzeigen. Wenn wir diese Cookies („Werbe-Cookies“) verwenden, geschieht dies nur, wenn du der Verwendung von Cookies durch Klicken auf „AKZEPTIEREN“ zugestimmt hast. Bitte beachte, dass du Werbung siehst, die für dich weniger relevant ist und bestimmte Funktionen der Website möglicherweise nicht wie beabsichtigt funktionieren, wenn du die Verwendung von Cookies ablehnst. Du kannst deine Meinung jederzeit ändern und deine Auswahl in unserer Datenschutzerklärung entsprechend anpassen. Weitere Informationen zu den von uns verwendeten Cookies findest du in unserer Datenschutzerklärung. Informationen über unsere Partner, die Werbe-Cookies auf unserer Website einsetzen, findest du in der nachfolgenden Partnerliste.',
        buttonAccept: 'AKZEPTIEREN',
        buttonLearnMore: 'MEHR ERFAHREN',
        buttonReject: 'ABLEHNEN',
        privacyLinkText: 'Datenschutzerklärung',
        // privacyLink: 'http://de.wikia.com/Datenschutz',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Partnerliste',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    en: {
        headline: 'This site uses cookies',
        bodyParagraphScreenOne: 'Fandom and our partners use technology such as cookies on our site. To consent to these activities, click / tap "ACCEPT." For additional options, please select "LEARN MORE."',
        bodyPargraphScreenTwo: 'Fandom and our partners use technology such as cookies on our site to personalize content and ads, provide social media features, and analyze our traffic. In particular, we want to draw your attention to cookies which are used to market to you, or provide personalized ads to you. Where we use these cookies (“advertising cookies”), we do so only where you have consented to our use of such cookies by clicking / tapping "ACCEPT" below. Note that if you select reject, you may see ads that are less relevant to you and certain features of the site may not work as intended. You can change your mind and revisit your consent choices at any time by visiting our Privacy Policy. For more information about the cookies we use, please see our Privacy Policy. For information about our partners using advertising cookies on our site, please see the Partner List below.',
        buttonAccept: 'ACCEPT',
        buttonLearnMore: 'LEARN MORE',
        buttonReject: 'REJECT',
        privacyLinkText: 'Privacy Policy',
        privacyLink: 'https://www.fandom.com/privacy-policy',
        partnerLinkText: 'Partner List',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    es: {
        headline: 'Este sitio utiliza cookies',
        bodyParagraphScreenOne: 'Fandom y sus socios utilizan herramientas como las cookies en este sitio. Para aceptar el uso de estas herramientas, haz clic en "ACEPTAR". Para ver otras opciones, por favor selecciona "MÁS INFORMACIÓN".',
        bodyPargraphScreenTwo: 'Fandom y sus socios utilizan herramientas como las cookies en este sitio para personalizar el contenido y los anuncios, así como proporcionar funcionalidades para redes sociales y analizar el tráfico. En particular, queremos llamar tu atención sobre las cookies que se utilizan para comercializar o proporcionar anuncios personalizados. Solo utilizamos estas cookies ("cookies de publicidad"), donde hayas consentido el uso de tales cookies seleccionando "ACEPTAR". Ten en cuenta que si seleccionas la opción de rechazar, puede que veas anuncios que son menos relevantes y que ciertas funcionalidades del sitio no funcionen según lo previsto. Puedes cambiar de opinión y revisar las opciones de consentimiento en cualquier momento visitando nuestra política de privacidad. Para obtener más información acerca de las cookies que utilizamos, por favor revisa nuestra política de privacidad. Para obtener más información sobre los socios que utilizan cookies de publicidad en nuestro sitio, consulta la lista de socios abajo.',
        buttonAccept: 'ACEPTAR',
        buttonLearnMore: 'MÁS INFORMACIÓN',
        buttonReject: 'RECHAZAR',
        privacyLinkText: 'Política de privacidad',
        // privacyLink: 'http://es.wikia.com/Pol%C3%ADtica_de_Privacidad',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista de socios',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    fr: {
        headline: 'Ce site utilise des cookies.',
        bodyParagraphScreenOne: 'Fandom et ses partenaires se servent de technologies telles que les cookies sur le site. Pour consentir à ces activités, cliquez / appuyez sur "ACCEPTER". Pour plus d\'informations sur les options supplémentaires, sélectionnez "EN SAVOIR PLUS".',
        bodyPargraphScreenTwo: 'Fandom et ses partenaires se servent de technologies telles que les cookies sur le site pour personnaliser le contenu et les publicités, fournir des fonctionnalités de réseau social et analyser le trafic. Nous souhaitons attirer plus particulièrement votre attention sur les cookies utilisés pour vous proposer des publicités personnalisées. Nous utilisons ces cookies (“cookies publicitaires”) uniquement si vous avez consenti à leur utilisation en cliquant / appuyant sur "ACCEPTER" ci-dessous. Notez que si vous sélectionnez Refuser, il se peut que des publicités moins pertinentes s\'affichent pour vous et que certaines fonctionnalités du site ne fonctionnent pas comme prévu. Si vous changez d\'avis, vous pouvez revenir sur votre choix à tout moment en consultant notre politique de confidentialité. Pour plus d\'informations sur les cookies utilisés, voir notre Politique de confidentialité. Pour plus d\'informations sur nos partenaires utilisant des cookies publicitaires sur le site, voir la Liste des partenaires ci-dessous.',
        buttonAccept: 'ACCEPTER',
        buttonLearnMore: 'EN SAVOIR PLUS',
        buttonReject: 'REFUSER',
        privacyLinkText: 'Politique de confidentialité',
        // privacyLink: 'http://fr.wikia.com/Politique_de_confidentialit%C3%A9',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Liste des partenaires',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    it: {
        headline: 'Questo sito utilizza i cookie',
        bodyParagraphScreenOne: 'Fandom e i nostri partner usano sul nostro sito tecnologie come i cookie. Per acconsentire a queste attività, clicca "ACCETTO". Per opzioni aggiuntive, seleziona "ULTERIORI INFORMAZIONI".',
        bodyPargraphScreenTwo: 'Fandom e i nostri partner usano tecnologie come i cookie sul nostro sito per personalizzare contenuti, annunci, fornire funzioni social e analizzare il nostro traffico. Vorremmo concentrare la tua attenzione in particolar modo sui cookie che sono usati a scopi commerciali o per fornire annunci personalizzati per te. Quando usiamo questi cookie ("cookie pubblicitari"), lo facciamo solo se hai acconsentito al loro uso selezionando "ACCETTO" qui sotto. Considera che nel caso di rifiuto potresti vedere annunci meno pertinenti per te e certe funzioni del sito potrebbero non funzionare come previsto. Puoi cambiare idea e rivisitare le tue scelte di consenso in qualsiasi momento visitando la nostra informativa sulla privacy. Per ulteriori informazioni sui cookie che usiamo, si prega di consultare la nostra informativa sulla privacy. Per informazioni sui nostri partner che usano cookie per la pubblicità sul nostro sito, consulta per favore la lista dei partner qui sotto.',
        buttonAccept: 'ACCETTO',
        buttonLearnMore: 'ULTERIORI INFORMAZIONI',
        buttonReject: 'RIFIUTO',
        privacyLinkText: 'Informativa sulla privacy',
        // privacyLink: 'http://it.community.wikia.com/wiki/Wiki_della_Community:Privacy',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista dei partner',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    ja: {
        headline: 'Cookie情報の利用について',
        bodyParagraphScreenOne: 'Fandomとそのパートナーは、このサイトでCookieなどのテクノロジーを使用しています。このような行為に同意する場合は、「同意する」をクリックしてください。 その他のオプションをご覧になるには、「詳細を見る」をお選びください。',
        bodyPargraphScreenTwo: 'Fandomとそのパートナーは、Cookieなどのテクノロジーを使用し、個々のユーザーに合わせたコンテンツや広告のカスタマイズ、ソーシャルメディア機能の提供、トラフィックの分析などをしています。 ここでいうCookieとは、ユーザーのターゲティング、あるいは個々のユーザーの好みなどに応じた広告のカスタマイズのために使用するCookieのことを指します。 Fandomとパートナーは、ユーザーが下の「同意する」をクリックして、FandomやパートナーがこうしたCookieを使用することに同意した場合のみ、こうしたCookie（「広告Cookie」）を使用します。 なお、拒否を選択した場合は、関連性の低い広告が表示される可能性や、このサイトの一部の機能が正常に動作しない可能性があることにご注意ください。 この選択は、プライバシー・ポリシーのページにアクセスして、後からいつでも変更していただけます。 Fandomとパートナーが使用するCookieについて詳しくは、「プライバシー・ポリシー」をご覧ください。 このサイトで広告Cookieを使用しているFandomのパートナーについて詳しくは、下の「パートナー・リスト」をご覧ください。',
        buttonAccept: '同意する',
        buttonLearnMore: '詳細を見る',
        buttonReject: '同意しない',
        privacyLinkText: 'プライバシー・ポリシー',
        // privacyLink: 'http://ja.wikia.com/%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E3%83%BB%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'パートナー・リスト',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    pl: {
        headline: 'Ta witryna używa ciasteczek',
        bodyParagraphScreenOne: 'Fandom i nasi partnerzy korzystają z technologii, takich jak ciasteczka, na naszej stronie. Aby wyrazić zgodę na takie działania, kliknij „AKCEPTUJĘ”. W celu zapoznania się z dodatkowymi opcjami, wybierz „DOWIEDZ SIĘ WIĘCEJ”.',
        bodyPargraphScreenTwo: 'Fandom i nasi partnerzy korzystają z technologii, takich jak ciasteczka, na naszej stronie, aby personalizować treści i reklamy, dostarczać funkcje mediów społecznościowych oraz by analizować nasze statystyki odwiedzin. W szczególności chcemy zwrócić uwagę na ciasteczka, które są używane do kierowania do ciebie marketingu lub zapewnienia spersonalizowanych reklam. W przypadku, gdy używamy ciasteczek („reklamowe ciasteczka”), robimy to wyłącznie tam, gdzie uzyskaliśmy twoją zgodę na ich używanie poprzez kliknięcie „AKCEPTUJĘ” poniżej. Zwróć uwagę, że jeśli wybierzesz opcję odrzuć, możesz zobaczyć reklamy, które są mniej odpowiednie dla ciebie, a niektóre funkcje witryny mogą nie działać zgodnie z ich przeznaczeniem. Możesz zmienić zdanie i ponownie przejrzeć zgody w dowolnym momencie, odwiedzając naszą politykę prywatności. Aby uzyskać więcej informacji na temat ciasteczek, z których korzystamy, zapoznaj się z naszą polityką prywatności. Aby uzyskać informacje o naszych partnerach wykorzystujących reklamowe ciasteczka na naszej stronie, zobacz poniżej listę partnerów.',
        buttonAccept: 'AKCEPTUJĘ',
        buttonLearnMore: 'DOWIEDZ SIĘ WIĘCEJ',
        buttonReject: 'ODRZUĆ',
        privacyLinkText: 'Polityka prywatności',
        // privacyLink: 'http://pl.wikia.com/Polityka_Prywatno%C5%9Bci',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista partnerów',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    pt: {
        headline: 'Este site utiliza cookies',
        bodyParagraphScreenOne: 'O Fandom e nossos parceiros usam tecnologias tais como cookies em nosso site. Para aceitar essas atividades, clique em "ACEITAR". Para opções adicionais, por favor selecione "SAIBA MAIS".',
        bodyPargraphScreenTwo: 'O Fandom e seus parceiros usam tecnologia tais como cookies no nosso site para personalizar o conteúdo e os anúncios, oferecer recursos de mídia social e analisar o tráfego. Em particular, queremos chamar a atenção para os cookies que são utilizados para oferecer algo a você, ou para oferecer anúncios personalizados. Nós usamos esses cookies ("cookies de publicidade"), apenas se você tenha consentido o uso ao clicar "ACEITAR" abaixo. Observe que se você selecionar rejeitar, você pode ver anúncios menos relevantes para você e certas características do site podem não funcionar conforme o esperado. Você pode mudar de ideia e revisitar as suas escolhas de consentimento a qualquer momento, visitando a nossa política de privacidade. Para obter mais informações sobre os cookies que usamos, por favor consulte a nossa Política de privacidade. Para obter mais informações sobre nossos parceiros usando cookies de publicidade no nosso site, por favor, veja abaixo a lista de parceiros.',
        buttonAccept: 'ACEITAR',
        buttonLearnMore: 'SAIBA MAIS',
        buttonReject: 'REJEITAR',
        privacyLinkText: 'Política de privacidade',
        // privacyLink: 'http://pt-br.wikia.com/wiki/Pol%C3%ADtica_de_Privacidade',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista de parceiros',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    ru: {
        headline: 'На этом сайте используются файлы cookie',
        bodyParagraphScreenOne: 'Мы и наши партнёры используем на этом сайте различные технологии, такие как файлы cookies. Предоставьте своё согласие, нажав «ПРИНЯТЬ». Чтобы получить дополнительную информацию, нажмите «УЗНАТЬ БОЛЬШЕ».',
        bodyPargraphScreenTwo: 'Мы и наши партнеры используем на этом сайте технологии, такие как файлы cookie, для персонализации контента и рекламы, предоставления функций социальных сетей и анализа трафика. В частности, обращаем ваше внимание на файлы cookie, которые применяются для показа рекламы или персонализированных объявлений. Мы используем файлы cookies («рекламные файлы cookies») только там, где вы дали своё согласие на использование таких файлов, нажав «ПРИНЯТЬ». Помните, что если отказаться от использования файлов cookie, вам могут показываться менее релевантные рекламные объявления, а некоторые функции сайта могут работать не должным образом. Вы можете изменить своё решение в любое время на странице политики конфиденциальности. Для получения более подробной информации о файлах cookie ознакомьтесь с нашей Политикой конфиденциальности. Для получения информации о наших партнёрах, использующих рекламные файлы cookies, ознакомьтесь со списком партнёров ниже.',
        buttonAccept: 'ПРИНЯТЬ',
        buttonLearnMore: 'УЗНАТЬ БОЛЬШЕ',
        buttonReject: 'ОТКАЗАТЬСЯ',
        privacyLinkText: 'Конфиденциальность',
        // privacyLink: 'http://ru.wikia.com/%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B4%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Список партнеров',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    'zh': {
        headline: '本网站使用Cookie',
        bodyParagraphScreenOne: 'Fandom和我们的合作商在网站中使用了Cookie等技术。 点击“接受”表示您同意这些活动。 查看更多讯息，请点击“了解更多”。',
        bodyPargraphScreenTwo: 'Fandom以及其合作伙伴在网站上将使用Cookie等技术来定制化内容和广告，提供社交媒体功能，以及分析网站流量。 我们尤其希望您能够注意到Cookie将用于为您提供个性化的广告。 如果您同意我们使用这些Cookie（“广告Cookie”），可以点击下面的“接受”按钮。 请注意，如果您选择“拒绝”，您可能会看到与您喜好不太相关的广告，并且网站的某些功能可能无法按正常工作。 您可以随时通过访问我们的隐私政策改变您的想法并重新选择是否同意这项条款。 有关我们使用Cookie的详细信息，请参阅我们的隐私政策。 关于我们的合作伙伴使用我们网站上的广告Cookie信息，请参阅下面的合作伙伴列表。',
        buttonAccept: '接受',
        buttonLearnMore: '了解更多',
        buttonReject: '拒绝',
        privacyLinkText: '隐私政策',
        // privacyLink: 'http://zh.wikia.com/wiki/%E9%9A%90%E7%A7%81%E6%9D%83%E6%96%B9%E9%92%88?variant=zh-hans',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: '合作伙伴列表',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    'zh-tw': {
        headline: '本網站使用Cookie',
        bodyParagraphScreenOne: 'Fandom和我們的合作夥伴在網站中使用了Cookie等技術。 按「接受」表示您同意這些活動。 查閱更多訊息，請按「瞭解更多」。',
        bodyPargraphScreenTwo: 'Fandom以及其合作夥伴在網站上將使用Cookie等技術來定制化內容和廣告，提供社交媒體功能，以及分析網站流量。 我們尤其希望您能夠注意到Cookie將用於為您提供訂制廣告。如果您同意我們使用這些Cookie（「廣告Cookie」），可以按下面的「接受」按鈕。 請注意，如果您選擇「拒絕」，您可能會看到與您喜好不太相關的廣告，並且網站的某些功能可能無法按正常工作。 您可以隨時透過訪問我們的隱私政策改變您的想法並重新選擇是否同意這項條款。 有關我們使用Cookie的詳細內容，請參閱我們的隱私政策。 關於我們的合作夥伴使用我們網站上的廣告Cookie訊息，請參閱下面的合作夥伴清單。',
        buttonAccept: '接受',
        buttonLearnMore: '閱讀更多',
        buttonReject: '拒絕',
        privacyLinkText: '隱私政策',
        // privacyLink: 'http://zh.wikia.com/wiki/%E9%9A%90%E7%A7%81%E6%9D%83%E6%96%B9%E9%92%88?variant=zh-hant',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: '合作廠商列表',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    'zh-hk': {
      headline: '本網站使用Cookie',
      bodyParagraphScreenOne: 'Fandom和我們的合作夥伴在網站中使用了Cookie等技術。 按「接受」表示您同意這些活動。 查閱更多訊息，請按「瞭解更多」。',
      bodyPargraphScreenTwo: 'Fandom以及其合作夥伴在網站上將使用Cookie等技術來定制化內容和廣告，提供社交媒體功能，以及分析網站流量。 我們尤其希望您能夠注意到Cookie將用於為您提供訂制廣告。如果您同意我們使用這些Cookie（「廣告Cookie」），可以按下面的「接受」按鈕。請注意，如果您選擇「拒絕」，您可能會看到與您喜好不太相關的廣告，並且網站的某些功能可能無法按正常工作。 您可以隨時透過訪問我們的隱私政策改變您的想法並重新選擇是否同意這項條款。 有關我們使用Cookie的詳細內容，請參閱我們的隱私政策。 關於我們的合作夥伴使用我們網站上的廣告Cookie訊息，請參閱下面的合作夥伴清單。',
      buttonAccept: '接受',
      buttonLearnMore: '閱讀更多',
      buttonReject: '拒絕',
      privacyLinkText: '隱私政策',
      // privacyLink: 'http://zh.wikia.com/wiki/%E9%9A%90%E7%A7%81%E6%9D%83%E6%96%B9%E9%92%88?variant=zh-hant',
      privacyLink: 'https://www.fandom.com/privacy-policy',
      partnerLinkText: '合作夥伴清單',
      partnerLink: 'https://www.fandom.com/partner-list',
    },
};

export default class ContentManager {
    constructor(lang) {
        this.content = langToContent[lang] || langToContent.en;
    }
}
