export const langToContent = {
    de: {
        headline: 'Diese Website verwendet Cookies',
        bodyParagraphs: [
            'Fandom und unsere Partner verwenden auf unserer Website Technologien wie z. B. Cookies. Um dem zuzustimmen, klicke bitte auf „WERBE-COOKIES AKZEPTIEREN“. Per opzioni aggiuntive, seleziona "ULTERIORI INFORMAZIONI".',
        ],
        buttonAccept: 'WERBE-COOKIES AKZEPTIEREN',
        buttonLearnMore: '',
        buttonReject: 'WERBE-COOKIES ABLEHNEN',
        privacyLinkText: 'Datenschutzerklärung von FANDOM',
        // privacyLink: 'http://de.wikia.com/Datenschutz',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Partnerliste',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    en: {
        headline: 'This site uses cookies',
        bodyParagraphScreenOne: 'Fandom and our partners use technology such as cookies on our site. To consent to these activities, click / tap "ACCEPT ADVERTISING COOKIES". For additional options, please select "LEARN MORE".',
        bodyPargraphScreenTwo: 'Fandom and our partners use technology such as cookies on our site to personalize content and ads, provide social media features, and analyze our traffic. In particular, we want to draw your attention to cookies which are used to market to you, or provide personalized ads to you. Where we use these cookies (“advertising cookies”), we do so only where you have consented to our use of such cookies by clicking / tapping "ACCEPT ADVERTISING COOKIES" below. Note that if you select reject, you may see ads that are less relevant to you and certain features of the site may not work as intended. You can change your mind and revisit your consent choices at any time by visiting our privacy policy. For more information about the cookies we use, please see our Privacy Policy. For information about our partners using advertising cookies on our site, please see the Partner List below.',
        buttonAccept: 'ACCEPT ADVERTISING COOKIES',
        buttonLearnMore: 'LEARN MORE',
        buttonReject: 'REJECT ADVERTISING COOKIES',
        privacyLinkText: 'Privacy Policy',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Partner List',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    es: {
        headline: 'Este sitio utiliza cookies',
        bodyParagraphs: [
            'FANDOM y nuestros socios utilizan tecnología como cookies en nuestro sitio para personalizar el contenido y anuncios, proporcionar funcionalidades de redes sociales y analizar nuestro tráfico. ',
            'En particular, queremos llamar tu atención sobre los cookies que se utilizan para comercializar o proporcionar anuncios personalizados. Cuando utilizamos estos cookies ("cookies de publicidad"), lo hacemos solamente donde tú hayas consentido el uso de tales cookies seleccionando ""ACEPTAR COOKIES DE PUBLICIDAD"". Toma en cuenta que si seleccionas rechazar, puede que veas los anuncios que son menos relevantes y que ciertas funcionalidades del sitio no funcionen según lo previsto.',
            'Puedes cambiar de opinión y revisar las opciones de consentimiento en cualquier momento visitando nuestra política de privacidad. Para obtener más información acerca de los cookies que utilizamos, por favor revisa nuestra política de privacidad. Para obtener más información sobre nuestros socios utilizando las cookies de publicidad en nuestro sitio, consulta la lista de socios abajo.',
        ],
        buttonAccept: 'ACEPTAR LOS COOKIES DE PUBLICIDAD',
        buttonLearnMore: '',
        buttonReject: 'RECHAZAR LOS COOKIES DE PUBLICIDAD',
        privacyLinkText: 'Política de privacidad FANDOM',
        // privacyLink: 'http://es.wikia.com/Pol%C3%ADtica_de_Privacidad',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista de socios',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    fr: {
        headline: 'Ce site utilise des cookies.',
        bodyParagraphs: [
            'FANDOM et ses partenaires se servent de technologies telles que les cookies sur le site pour personnaliser le contenu et les publicités, fournir des fonctionnalités de réseau social et analyser le trafic.',
            'Nous souhaitons attirer plus particulièrement votre attention sur les cookies utilisés pour vous proposer des publicités personnalisées. Nous utilisons ces cookies (“cookies publicitaires”) uniquement si vous avez consenti à leur utilisation en cochant la case "ACCEPTER LES COOKIES PUBLICITAIRES" ci-dessous. Notez que si vous sélectionnez Refuser, il se peut que des publicités moins pertinentes s\'affichent pour vous et que certaines fonctionnalités du site ne fonctionnent pas comme prévu.',
            'Si vous changez d\'avis, vous pouvez revenir sur votre choix à tout moment en consultant notre politique de confidentialité. Pour plus d\'informations sur les cookies utilisés, voir notre Politique de confidentialité. Pour plus d\'informations sur nos partenaires utilisant des cookies publicitaires sur le site, voir la Liste des partenaires ci-dessous.',
        ],
        buttonAccept: 'ACCEPTER LES COOKIES PUBLICITAIRES',
        buttonLearnMore: '',
        buttonReject: 'REFUSER LES COOKIES PUBLICITAIRES',
        privacyLinkText: 'Politique de confidentialité de FANDOM',
        // privacyLink: 'http://fr.wikia.com/Politique_de_confidentialit%C3%A9',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Liste des partenaires',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    it: {
        headline: 'Questo sito utilizza i cookie',
        bodyParagraphs: [
            'FANDOM e i nostri partner usano tecnologie come i cookie sul nostro sito per personalizzare contenuti, annunci, fornire funzioni social e analizzare il nostro traffico.',
            'Vorremmo concentrare la tua attenzione in particolar modo sui cookie che sono usati a scopi commerciali o per fornire annunci personalizzati per te. Quando usiamo questi cookie ("cookie commerciali"), lo facciamo solo se hai acconsentito al loro uso selezionando "ACCETTA COOKIE COMMERCIALI" qui sotto. Considera che nel caso di rifiuto potresti vedere annunci meno pertinenti per te e certe funzioni del sito potrebbero non funzionare come previsto.',
            'Puoi cambiare idea e rivisitare le tue scelte di consenso in qualsiasi momento visitando la nostra informativa sulla privacy. Per ulteriori informazioni sui cookie che usiamo, si prega di consultare la nostra informativa sulla privacy. Per informazioni sui nostri partner che usano cookie per la pubblicità sul nostro sito, consulta per favore la lista dei partner qui sotto.',
        ],
        buttonAccept: 'ACCETTA COOKIE COMMERCIALI',
        buttonLearnMore: '',
        buttonReject: 'RIFIUTA COOKIE COMMERCIALI',
        privacyLinkText: 'Informativa sulla privacy di FANDOM',
        // privacyLink: 'http://it.community.wikia.com/wiki/Wiki_della_Community:Privacy',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista dei partner',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    ja: {
        headline: 'cookie情報の利用について',
        bodyParagraphs: [
            'FANDOMおよびパートナーは当サイトでcookieなどの技術を、コンテンツや広告のユーザーに合わせたカスタマイズ、ソーシャルメディア機能の提供やトラフィックの分析に使用しています。',
            'この機能はアクセス動向の把握による、ユーザーの目を引く、よりカスタマイズされた広告の表示を目的とするものです。 FANDOMとパートナーがこうしたcookie（広告用cookie）を使用するのは、ユーザーが下の「広告用cookieを許可する」をクリックして、同意した場合のみになります。 なお拒否を選択した場合に、関連性の低い広告が表示される可能性や当サイトの一部の機能が正常に動作しない場合がありますのでご注意ください。 ',
            'この設定はプライバシー・ポリシーのページにアクセスして、後からいつでも変更可能です。 FANDOMとパートナーが使用するcookieについて詳しくは、プライバシー・ポリシーをご覧ください。 また、このサイトで広告用Cookieを使用しているFANDOMのパートナーについて詳しくは、下記のパートナー・リストをご覧ください。',
        ],
        buttonAccept: '広告用cookieを許可',
        buttonLearnMore: '',
        buttonReject: '広告用cookieを拒否',
        privacyLinkText: 'FANDOMプライバシー・ポリシー',
        // privacyLink: 'http://ja.wikia.com/%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E3%83%BB%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'パートナー・リスト',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    pl: {
        headline: 'Ta witryna używa plików cookie',
        bodyParagraphs: [
            'FANDOM i nasi partnerzy korzystają z technologii takich jak pliki cookie na naszej stronie, aby personalizować treści i reklamy, dostarczać funkcje mediów społecznościowych oraz by analizować nasze statystyki odwiedzin.',
            'W szczególności chcemy zwrócić uwagę na pliki cookie, które są używane do kierowania do ciebie marketingu lub zapewnienia ci spersonalizowanych reklam. W przypadku, gdy używamy plików cookies („reklamowe cookies”), robimy to wyłączinie tam gdzie uzyskaliśmy twoją zgodę na używanie tych plików cookies poprzez zaznaczenie „AKCEPTUJĘ REKLAMOWE PLIKI COOKIES” poniżej. Zwróć uwagę, że jeśli wybierzesz opcję odrzuć, możesz zobaczyć reklamy, które są mniej odpowiednie dla ciebie, a niektóre funkcje witryny mogą nie działać zgodnie z przeznaczeniem.',
            'Możesz zmienić zdanie i ponownie przejrzeć zgody w dowolnym momencie, odwiedzając naszą politykę prywatności. Aby uzyskać więcej informacji na temat plików cookies, z których korzystamy, zapoznaj się z naszą polityką prywatności. Aby uzyskać informacje o naszych partnerach wykorzystujących reklamowe pliki cookies na naszej stronie zobacz listę partnerów poniżej.',
        ],
        buttonAccept: 'AKCEPTUJĘ REKLAMOWE PLIKI COOKIES',
        buttonLearnMore: '',
        buttonReject: 'ODRZUCAM REKLAMOWE PLIKI COOKIES',
        privacyLinkText: 'Polityka prywatności Fandomu',
        // privacyLink: 'http://pl.wikia.com/Polityka_Prywatno%C5%9Bci',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista partnerów',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    pt: {
        headline: 'Este site utiliza cookies',
        bodyParagraphs: [
            'O FANDOM e seus parceiros usam tecnologia tais como cookies no nosso site para personalizar o conteúdo e os anúncios, oferecer recursos de mídia social e analisar o tráfego.',
            'Em particular, queremos chamar a atenção para os cookies que são utilizados para oferecer algo a você ou para oferecer anúncios personalizados. Nós usamos esses cookies ("cookies de publicidade"), apenas se você tenha consentido o uso ao clicar ""ACEITAR COOKIES DE PUBLICIDADE"" abaixo. Observe que se você selecionar rejeitar, você pode ver anúncios menos relevantes para você e certas características do site podem não funcionar conforme o esperado. ',
            'Você pode mudar de ideia e revisitar as suas escolhas de consentimento a qualquer momento, visitando a nossa política de privacidade. Para obter mais informações sobre os cookies que usamos, por favor consulte a nossa Política de privacidade. Para obter mais informações sobre nossos parceiros usando cookies de publicidade no nosso site, por favor, veja abaixo a lista de parceiros.',
        ],
        buttonAccept: 'ACEITAR COOKIES DE PUBLICIDADE',
        buttonLearnMore: '',
        buttonReject: 'REJEITAR COOKIES DE PUBLICIDADE',
        privacyLinkText: 'Política de privacidade do FANDOM',
        // privacyLink: 'http://pt-br.wikia.com/wiki/Pol%C3%ADtica_de_Privacidade',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Lista de parceiros',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    ru: {
        headline: 'На этом сайте используются файлы cookie',
        bodyParagraphs: [
            'Мы и наши партнёры используем на этом сайте технологии, такие как файлы cookies, для персонализации контента и рекламы, предоставления функций социальных сетей и анализа трафика. ',
            'В частности, обращаем ваше внимание на файлы cookies, которые применяются для показа рекламы, в том числе, персонализированной рекламы. Мы используем файлы cookies («рекламные файлы cookies») только там, где вы дали своё согласие на использование файлов cookies, нажав на кнопку «ПРИНЯТЬ РЕКЛАМНЫЕ COOKIES» внизу. Помните, что если отказаться от использования файлов cookies, вам могут показывать менее релевантные рекламные объявления, а некоторые функции сайта могут работать не должным образом. ',
            'Вы можете изменить решение о предоставлении или непредоставлении своего согласия в любое время на странице политики конфиденциальности. Для получения более подробной информации о файлах cookies ознакомьтесь с нашей политикой конфиденциальности. Для получения информации о наших партнёрах, использующих рекламные файлы cookies, ознакомьтесь со списком партнёров ниже.',
        ],
        buttonAccept: 'ПРИНЯТЬ РЕКЛАМНЫЕ COOKIE',
        buttonLearnMore: '',
        buttonReject: 'ОТКАЗАТЬСЯ ОТ РЕКЛАМНЫХ COOKIE',
        privacyLinkText: 'Политика конфиденциальности ФЭНДОМА',
        // privacyLink: 'http://ru.wikia.com/%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B4%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Список партнеров',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    'zh': {
        headline: '本网站使用Cookie',
        bodyParagraphs: [
            'FANDOM以及其合作伙伴在网站上将使用Cookie等技术来定制化内容和广告，提供社交媒体功能，以及分析网站流量。',
            '我们尤其希望您能够注意到Cookie将用于为您提供个性化的广告。 如果您同意我们使用这些Cookie（“广告Cookie”），可以点击下面的“接收广告Cookie”按钮。 请注意，如果您选择“拒绝”，您可能会看到与您喜好不太相关的广告，并且网站的某些功能可能无法正常工作。',
            '您可以随时通过访问我们的隐私政策改变您的想法并重新选择是否同意这项条款。 有关我们使用Cookie的详细信息，请参阅我们的隐私政策。 关于我们的合作伙伴使用我们网站上的广告Cookie信息，请参阅下面的合作伙伴列表。',
        ],
        buttonAccept: '接受广告Cookie',
        buttonLearnMore: '',
        buttonReject: '拒绝广告Cookie',
        privacyLinkText: 'FANDOM隐私政策',
        // privacyLink: 'http://zh.wikia.com/wiki/%E9%9A%90%E7%A7%81%E6%9D%83%E6%96%B9%E9%92%88?variant=zh-hans',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: '合作伙伴列表',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    'zh-tw': {
        headline: '本網站使用Cookie',
        bodyParagraphs: [
            'FANDOM以及其合作廠商在網站上會使用Cookie等技術來使內容和廣告個人化、提供社交媒體功能，以及分析網站流量。',
            '我們尤其希望您能夠注意到Cookie將用於行銷，為您提供個人化的廣告。 如果您同意我們使用這些Cookie（「廣告Cookie」），可以按下面的「接收廣告Cookie」按鈕。 請注意，如果您選擇「拒絕」，您可能會看到與您的喜好不太相關的廣告，並且網站的某些功能可能無法正常運作。',
            '您可以隨時透過訪問我們的隱私權方針頁面，改變您的想法並重新選擇是否同意這個選項。  有關我們使用Cookie的詳細內容，請參閱我們的隱私權方針。 關於會使用我們網站上廣告Cookie的合作廠商資訊，請參見下面的合作廠商列表。',
        ],
        buttonAccept: '接受廣告Cookie',
        buttonLearnMore: '',
        buttonReject: '拒絕廣告Cookie',
        privacyLinkText: 'FANDOM隱私政策',
        // privacyLink: 'http://zh.wikia.com/wiki/%E9%9A%90%E7%A7%81%E6%9D%83%E6%96%B9%E9%92%88?variant=zh-hant',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: '合作廠商列表',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
    'zh-hk': {
        headline: '本網站使用Cookie',
        bodyParagraphs: [
            'FANDOM以及其合作廠商在網站上會使用Cookie等技術來使內容和廣告個人化、提供社交媒體功能，以及分析網站流量。',
            '我們尤其希望您能夠注意到Cookie將用於行銷，為您提供個人化的廣告。 如果您同意我們使用這些Cookie（「廣告Cookie」），可以按下面的「接收廣告Cookie」按鈕。 請注意，如果您選擇「拒絕」，您可能會看到與您的喜好不太相關的廣告，並且網站的某些功能可能無法正常運作。',
            '您可以隨時透過訪問我們的隱私權方針頁面，改變您的想法並重新選擇是否同意這個選項。  有關我們使用Cookie的詳細內容，請參閱我們的隱私權方針。 關於會使用我們網站上廣告Cookie的合作廠商資訊，請參見下面的合作廠商列表。',
        ],
        buttonAccept: '接受廣告Cookie',
        buttonLearnMore: '',
        buttonReject: '拒絕廣告Cookie',
        privacyLinkText: 'FANDOM隱私政策',
        // privacyLink: 'http://zh.wikia.com/wiki/%E9%9A%90%E7%A7%81%E6%9D%83%E6%96%B9%E9%92%88?variant=zh-hant',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: '合作廠商列表',
        partnerLink: 'http://fandom.wikia.com/partner-list',
    },
};

export default class ContentManager {
    constructor(lang) {
        this.content = langToContent[lang] || langToContent.en;
    }
}
