export const langToContent = {
    de: {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://de.wikia.com/Datenschutz',
        partnerLinkText: '',
        partnerLink: '',
    },
    en: {
        headline: 'This site uses cookies',
        bodyParagraphs: [
            'FANDOM and our partners use technology such as cookies on our site to personalize content and ads, provide social media features, and analyze our traffic.',
            'In particular, we want to draw your attention to cookies which are used to market to you, or provide personalized ads to you. Where we use these cookies (“advertising cookies”), we do so only where you have consented to our use of such cookies by ticking "ACCEPT ADVERTISING COOKIES" below. Note that if you select reject, you may see ads that are less relevant to you and certain features of the site may not work as intended.',
            'You can change your mind and revisit your consent choices at any time by visiting our privacy policy. For more information about the cookies we use, please see our Privacy Policy. For information about our partners using advertising cookies on our site, please see the Partner List below.',
        ],
        buttonAccept: 'ACCEPT ADVERTISING COOKIES',
        buttonReject: 'REJECT ADVERTISING COOKIES',
        privacyLinkText: 'Fandom Privacy Policy',
        privacyLink: 'http://www.wikia.com/Privacy_Policy',
        partnerLinkText: 'Partners List',
        partnerLink: '#',
    },
    es: {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://es.wikia.com/Pol%C3%ADtica_de_Privacidad',
        partnerLinkText: '',
        partnerLink: '',
    },
    fr: {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://fr.wikia.com/Politique_de_confidentialit%C3%A9',
        partnerLinkText: '',
        partnerLink: '',
    },
    it: {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://it.community.wikia.com/wiki/Wiki_della_Community:Privacy',
        partnerLinkText: '',
        partnerLink: '',
    },
    ja: {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://ja.wikia.com/%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E3%83%BB%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC',
        partnerLinkText: '',
        partnerLink: '',
    },
    pl: {
        headline: '',
        bodyParagraphs: [
        ],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://pl.wikia.com/Polityka_Prywatno%C5%9Bci',
        partnerLinkText: '',
        partnerLink: '',
    },
    pt: {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://pt-br.wikia.com/wiki/Pol%C3%ADtica_de_Privacidade',
        partnerLinkText: '',
        partnerLink: '',
    },
    ru: {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://pt-br.wikia.com/wiki/Pol%C3%ADtica_de_Privacidade',
        partnerLinkText: '',
        partnerLink: '',
    },
    'zh-hans': {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://zh.wikia.com/wiki/%E9%9A%90%E7%A7%81%E6%9D%83%E6%96%B9%E9%92%88?variant=zh-hans',
        partnerLinkText: '',
        partnerLink: '',
    },
    'zh-hant': {
        headline: '',
        bodyParagraphs: [],
        buttonAccept: '',
        buttonReject: '',
        privacyLinkText: '',
        privacyLink: 'http://zh-tw.wikia.com/wiki/%E9%9A%B1%E7%A7%81%E6%AC%8A%E6%96%B9%E9%87%9D',
        partnerLinkText: '',
        partnerLink: '',
    },
};

export default class ContentManager {
    constructor(lang) {
        this.content = langToContent[lang] || langToContent.en;
    }
}
