pipeline {
    agent {
        node {
            label 'docker-daemon'
        }
    }

    tools { nodejs "v9.9.0" }
    environment {
        imageName = "tracking-opt-in-demo"
        currentCommit = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
        dockerRepoUrl = "${env.DOCKER_REPO_URL}"
        serviceName = "${imageName}-${currentCommit}"
        appHost = "${env.APP_HOST_PREFIX}${currentCommit}${env.APP_HOST_SUFFIX}"
    }

    stages {

        stage('dependencies') {
            steps {
                sh "yarn install --frozen-lockfile"
            }
        }

        stage('BrowserStack') {
            steps {
                sh "BUILD_ID=${currentCommit} TEST_URL=${params.testUrl ?: "http://${appHost}"} yarn test:selenium"
            }
        }

    }

    post {
        success {
            sh 'echo hello'
//            slackSend (
//                    channel: '#cake-team-tech',
//                    color: 'good',
//                    failOnError: true,
//                    message: ":checkmark: tracking-opt-in ${params.pipeline} on ${params.branch} <${env.BUILD_URL}|succeeded>"
//            )
        }

        failure {
            sh 'echo hello'
        }

        always {
            script {
                allure([includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: 'reports/selenium/allure']]])
            }

            junit allowEmptyResults: true, testResults: 'reports/webdriver/junit/*.xml'
        }
    }
}
