name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    if: ${{ (!contains( github.event.pull_request.labels.*.name, 'Major change')) && (!contains( github.event.pull_request.labels.*.name, 'Minor change')) && (!contains( github.event.pull_request.labels.*.name, 'Patch change')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
